### ISSUE TITLE
GPL2 or GPL3?

### ISSUE THREAD

**Issue by suve** [burghardt/arptools#5]
The comments at the top of `src/*.c` files say:
```
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
```
Which suggests that the licence is GPL2 or later. The `debian/copyright` file seems to copy this text.

But then, `COPYING` contains:
```
GNU GENERAL PUBLIC LICENSE
   Version 3, 29 June 2007
```
Which suggests that the licence is GPL3. (Only GPL3? GPL3 or later?) 

-----

By the way, the licence headers in `*.c` files contain the outdated FSF address at Temple Place.
```
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
```
The current address is:
```
51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA
```

**Comment by burghardt** [comment]
I accidentally made the whole repo GPL v3.0+, except for actual code files that are still GPL v2.0+ (according to their headers). Dual licensing at its finest. ;-)

Let's make it a bit more complicated. What is the license of changes you have contributed? Is that GPL v2-only, GPL v2-or-later, GPL v3-only, or GPL v3-or-later?

**Comment by suve** [comment]
> What is the license of changes you have contributed? Is that GPL v2-only, GPL v2-or-later, GPL v3-only, or GPL v3-or-later?

Good question! I wrote the code assuming `GPL-2.0-or-later`, but I'm fine with all of these options.

**Comment by burghardt** [comment]
Thanks for pointing this out! Everything should be `GPL-2.0-or-later` now.
