### ISSUE TITLE
Should the programs be picky about interfaces?

### ISSUE THREAD

**Issue by suve** [burghardt/arptools#6]
Currently, all the programs assume they'll be working on Ethernet interfaces, but perform no checking whether the provided interface is an Ethernet one. [`pcap_datalink()`](https://npcap.com/guide/wpcap/pcap_datalink.html) can be used to get the link-layer header type for given device; this could then be used to:
1. Exit the program if the device is not an Ethernet device
2. Warn the user that the device does not seem to be an Ethernet device, and continue regardless
3. Maybe implement some support for non-Ethernet devices

**Comment by burghardt** [comment]
They are quite picky already. They won't work on non-Ethernet link types (i.e. GRE tunnels).

    # ip link add gre0 type gre
    # ip link set gre0 up
    # ./src/arpdiscover 1.2.3.4 5 gre0
    using interface gre0
    unknown physical layer type 0x30a
